# Generated by Django 5.1.5 on 2025-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pranikah',
            name='pembayaran',
            field=models.URLField(),
        ),
    ]
